name: pr
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

#       - name: Switch the action to use the Dockerfile.build
#         run: |
#           mv Dockerfile Dockerfile.runnable
#           mv Dockerfile.build Dockerfile
      - name: Replace scmfile.yaml With Custom Value
        uses: microsoft/variable-substitution@v1
        with:
          files: "test/scmfile.yaml"
        env:
          credential.usernamePassword.password: ${{ secrets.GITHUB_TOKEN }}
          credential.usernamePassword.username: ${{ github.actor }}
          scm.git.userRemoteConfig.url: ${{ github.repositoryUrl }}
          scm.git.branches.name: ${{ github.ref_name }}
          
      - name: Test; jenkinsfile-runner-prepackaged
        uses: ./
        with:
          jenkinsfile: "test/Jenkinsfile"
          plugins: "test/plugins.txt"
          scmfile: "test/scmfile.yaml"
