name: pr
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

#       - name: Switch the action to use the Dockerfile.build
#         run: |
#           mv Dockerfile Dockerfile.runnable
#           mv Dockerfile.build Dockerfile

      - name: Test; jenkinsfile-runner-prepackaged
        uses: ./
        with:
          jenkinsfile: "Jenkinsfile-helloworld"
          plugins: "base-plugins.txt"
          scmfiles: "base-scmfile.yaml"
