name: pr
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Switch the action to use the Dockerfile.build
        run: |
          mv prepackaged-jenkinsfile-runner/Dockerfile prepackaged-jenkinsfile-runner/Dockerfile.runnable
          mv prepackaged-jenkinsfile-runner/Dockerfile.build prepackaged-jenkinsfile-runner/Dockerfile

      - name: Test; jenkinsfile-runner-prepackaged
        uses: ./prepackaged-jenkinsfile-runner
        with:
          jenkinsfile: "prepackaged-jenkinsfile-runner/test/Jenkinsfile"
          pluginstxt: "prepackaged-jenkinsfile-runner/test/plugins.txt"
          command: "lint"
